### PR TITLE
Add configparser to requirements.txt

### PR DESCRIPTION
**Pull request by sethforprivacy**

### CODE REVIEW

**Comment by xjmzx** [comment]
I needed to add `import configparser` to get the script to work on Darwin

**Comment by Franky1** [comment]
Strange, configparser is part of the python standard library.
Which python version did you use?

**Comment by Franky1** [comment]
I fixed this in my latest pull request https://github.com/j4imefoo/nokyc/pull/20, which is not merged yet.

**Comment by j4imefoo** [comment]
Done

**Pull request merged**
